name: Send News Email Cron Job

permissions:
  contents: read

on:
  schedule:
    - cron: '0 13,1 * * *'  # Triggers at 8:00 AM and 8:00 PM ET
  workflow_dispatch:  # Allows manual runs for testing

jobs:
  send_news_email:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run cron script
        run: python -u run_cron.py
        env:
          MY_SECRET_API_KEY: ${{ secrets.MY_SECRET_API_KEY }}  # Securely pass API key
